# Generated by Django 6.0.6 on 2026-06-11 06:14

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(default='unknown-service', max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('execution_duration', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict, help_text='Unstructured log data in JSON format')),
            ],
        ),
    ]
