services:
  mongo:
    image: mongo:7
    container_name: logverse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  web:
    build: .
    container_name: logverse-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  dummy-app:
    image: traefik/whoami:v1.10
    container_name: sandbox-target-app
    labels:
      - "traefik.enable=true"
      # This matches http://dummy.localhost
      - "traefik.http.routers.dummy.entrypoints=web"
      - "traefik.http.routers.dummy.rule=Host(`dummy.localhost`)"
      - "traefik.http.services.dummy.loadbalancer.server.port=80"

  traefik:
    image: traefik:latest
    container_name: logverse-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # --- Access Log Configuration ---
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.json"
      - "--accesslog.format=json"
      - "--accesslog.bufferingsize=0"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik_logs:/var/log/traefik

  vector:
    image: timberio/vector:0.40.X-alpine
    container_name: logverse-vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - traefik_logs:/var/log/traefik:ro
    depends_on:
      - traefik
      - web

volumes:
  mongo_data:
  traefik_logs: # The shared pipeline bridge
